### ISSUE TITLE
Bug in formatTimespan function

### ISSUE THREAD

**Issue by eugene3141** [stellar-expert/claimable-balance-utils#1]
https://github.com/stellar-expert/claimable-balance-utils/blob/2abdfa8b9928e8fab248ed3544b3f33f3c75c2d5/src/claim-condtions-xdr-parser.js#L52-L62

Instead of 60 seconds, the function returns "1 hr".

**Comment by orbitlens** [comment]
Fixed.
Thanks for the heads up 👍

**Comment by eugene3141** [comment]
https://github.com/stellar-expert/claimable-balance-utils/blob/838a4eea85b0b2e400f834678610ccedf19a5b69/src/claim-condtions-xdr-parser.js#L59
There is an issue with the regular expression if the precision is 0.
30 days return " day", 150 days return "1 day".
